// actions types used in home page are defined here
export const OPEN_CLOSE_FORMS = 'OPEN_CLOSE_FORMS';

export const GET_DATA = 'GET_DATA';
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const REGISTER = 'REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';

export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_ERROR = 'FORGOT_PASSWORD_ERROR';

export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';

export const LOG_OUT = 'LOG_OUT';
export const TOGGLE_THEME = 'TOGGLE_THEME';

export const DOCTOR_PROFILE = 'DOCTOR_PROFILE';
export const DOCTOR_PROFILE_SUCCESS = 'DOCTOR_PROFILE_SUCCESS';
export const DOCTOR_PROFILE_ERROR = 'DOCTOR_PROFILE_ERROR';

export const NEW_SCHEDULE = 'NEW_SCHEDULE';
export const NEW_SCHEDULE_SUCCESS = 'NEW_SCHEDULE_SUCCESS';
export const NEW_SCHEDULE_ERROR = 'NEW_SCHEDULE_ERROR';

export const SIGNUP_ROLES = 'SIGNUP_ROLES';
export const SIGNUP_ROLES_SUCCESS = 'SIGNUP_ROLES_SUCCESS';
export const SIGNUP_ROLES_ERROR = 'SIGNUP_ROLES_ERROR';