export const GET_PROFILE_DATA = 'GET_PROFILE_DATA';
export const GET_PROFILE_DATA_SUCCESS = 'GET_PROFILE_DATA_SUCCESS';
export const GET_PROFILE_DATA_ERROR = 'GET_PROFILE_DATA_SUCCESS';

export const NEW_SCHEDULE = 'NEW_SCHEDULE';
export const NEW_SCHEDULE_SUCCESS = 'NEW_SCHEDULE_SUCCESS';
export const NEW_SCHEDULE_ERROR = 'NEW_SCHEDULE_ERROR';
